### ISSUE TITLE
Setting og:type has no action and is not saved

### ISSUE THREAD

**Issue by mahotilo** [juek/OpenGraph#3]
Is the issue's subject a bug or an option under construction?

**Comment by juek** [comment]
It will [change to 'blog' and 'article' with SimpleBlog pages](https://github.com/juek/OpenGraph/blob/master/OpenGraph.php#L468-L477)

**Comment by mahotilo** [comment]
And what about "product"? Can it be applied without the Simple blog?

**Comment by juek** [comment]
og product tags should also contain [price and currency](https://webcode.tools/open-graph-generator/product). Since Typesetter is not really an e-commerce platform I just didn't implement it.

**Comment by mahotilo** [comment]
Ok. Thx.

**Comment by juek** [comment]
I think other things like Twitter cards would be more important to be implemented but It's already quite a monster gpabox :)
